baseURL = "https://example.com/"
languageCode = "en-us"
title = "Data Gators Project"
theme = "personal-web_"
copyright="© Data Gators Project"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true


[params.intro]
  main = "DataGators :wave:"
  sub = "Help With Data Science at Allegheny College!"


[params.main]
  latestPublishHeader = "yey! My Latest Project!!"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
#  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = '¯\_(ツ)_/¯ Oops! Page not found!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
#  backgroundImage = '/images/treeLine.png' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  backgroundImage = '/images/main/bars_2.png' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash


  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  # logo = "/images/logos/dg_logo_short.png" # - default "/images/dg_logo_short.png"
  logo = "/images/logos/logo_500x500.png" 
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  glasses = "https://datagators.netlify.app/live/"
#  github = "https://github.com/"
#  twitter = "https://twitter.com/"
#  linkedin = "https://www.linkedin.com/in/"
#  medium = "https://medium.com/"
#  codepen = "https://codepen.io/"
#  facebook = "https://www.facebook.com/"
#  youtube = "https://www.youtube.com/"
#  instagram = "https://www.instagram.com/"
#  gitlab = "https://gitlab.com/"
#  keybase = "https://keybase.io/"

[params.contact]
  email = "obonhamcarter@allegheny.edu"
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -130

[[menu.main]]
  identifier = "resources"
  name = "Resources"
  title = "Resources"
  url = "/resources/"
  weight = -120

[[menu.main]]
  identifier = "learn"
  name = "Learn"
  title = "Learn"
  url = "/learn/"
  weight = -110

[[menu.main]]
  identifier = "Jupyter"
  name = "Jupyter"
  title = "Jupyter"
  url = "https://datagators.netlify.app/live/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true