# Simple Netlify configuration - Hugo only (backup)
# Use this if the main netlify.toml with JupyterLite fails

[build]
  publish = "public"
  command = "hugo --minify --gc"

[build.environment]
  HUGO_VERSION = "0.151.0"
  HUGO_BASEURL = "/"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "same-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"